#!/bin/bash

set -xe

export GOPATH=$PWD/go
export PATH=$GOPATH/bin:$PATH

go get github.com/tools/godep
source_dir="$(cd "$(dirname "$0")" && pwd)"
cd $source_dir/..
godep go build .
mv concourse-demo-app build-artifact
ls -lha build-artifact
